package com.recall.app.core.data.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * Represents a semantic vector embedding for a specific chunk of a note.
 *
 * Large notes are split into smaller chunks (e.g., paragraphs) so the AI can
 * retrieve highly relevant snippets rather than entire lengthy documents.
 * The embeddings are generated by an on-device ONNX model (e.g., MiniLM) and
 * stored as raw float byte arrays.
 *
 * If the parent note is deleted, its vector chunks are cascaded and deleted.
 *
 * @property chunkIndex The sequential position of this chunk within the parent note.
 * @property chunkText The raw string text that was vectorized.
 * @property embedding The semantic vector representation, stored as a byte array of IEEE 754 floats.
 */
@Entity(
    tableName = "vector_entries",
    foreignKeys = [
        ForeignKey(
            entity = Note::class,
            parentColumns = ["id"],
            childColumns = ["note_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("note_id")]
)
data class VectorEntry(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    @ColumnInfo(name = "note_id") val noteId: String,
    @ColumnInfo(name = "chunk_index") val chunkIndex: Int,
    @ColumnInfo(name = "chunk_text") val chunkText: String,
    val embedding: ByteArray, // Raw IEEE 754 float bytes
    @ColumnInfo(name = "updated_at") val updatedAt: Long = System.currentTimeMillis()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        other as VectorEntry
        if (id != other.id) return false
        if (!embedding.contentEquals(other.embedding)) return false
        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + embedding.contentHashCode()
        return result
    }
}
